name: DockerBuild

on:
  push:
    tags:
      - 'v*'

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to AliyunCS
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.ALI_USER  }}
          password: ${{ secrets.ALI_PASSWORD  }}
      -
        name: get image name
        run: |
          VERSION=$(cat ./version.txt)
          DOCKER_IMAGE_NAME=$(echo "docker.io/mereith/van-nav:v${VERSION}"')
          ALI_IMAGE_NAME=$(echo "registry.cn-shanghai.aliyuncs.com/mereith/van-nav:v${VERSION}"')
          echo ${VERSION}
          echo "::set-output name=DOCKER_IMAGE_NAME::$DOCKER_IMAGE_NAME"
          echo "::set-output name=ALI_IMAGE_NAME::$ALI_IMAGE_NAME"
        id: image-name
      - name: Build dasbboard image And Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm,linux/386,linux/s390x
          push: true
          tags: |
            ${{ steps.image-name.outputs.DOCKER_IMAGE_NAME }}
            ${{ steps.image-name.outputs.ALI_IMAGE_NAME }}